// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

// https://astro.build/config
export default defineConfig({
  // TODO(Phase 7): set the production URL once a deploy host is chosen.
  site: 'https://gears.dev',
  integrations: [
    starlight({
      title: 'Gears',
      description:
        'Documentation for Gears — a Rust runtime for composable, secure-by-default platform components.',
      // TODO(Phase 1): point at the real Gears source repository.
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/gears-rs/gears',
        },
      ],
      // Sidebar skeleton — the nine top-level sections from the IA.
      // Each section is autogenerated from its directory for now (Phase 1).
      // Explicit ordering/labels are tightened in Phase 3.
      sidebar: [
        {
          label: 'Introduction',
          items: [{ autogenerate: { directory: 'introduction' } }],
        },
        {
          label: 'Getting Started',
          items: [{ autogenerate: { directory: 'get-started' } }],
        },
        {
          label: 'Concepts',
          items: [{ autogenerate: { directory: 'concepts' } }],
        },
        {
          label: 'Guides',
          items: [{ autogenerate: { directory: 'guides' } }],
        },
        {
          label: 'Architecture',
          items: [{ autogenerate: { directory: 'architecture' } }],
        },
        {
          label: 'ADRs',
          items: [{ autogenerate: { directory: 'adrs' } }],
        },
        {
          label: 'Reference',
          items: [{ autogenerate: { directory: 'reference' } }],
        },
        {
          label: 'Examples',
          items: [{ autogenerate: { directory: 'examples' } }],
        },
        {
          label: 'Contributing',
          items: [{ autogenerate: { directory: 'contributing' } }],
        },
      ],
    }),
  ],
});
